@startuml

!include <C4/C4_Container>

Person(User, "Пользователь")
Person(EmployeeBack, "Сотрудник бэк-офиса")
Person(EmployeeFront, "Сотрудник фронт-офиса")
Person(CallCenter, "Сотрудник колл-центра банка")

System_Ext(PartnerCallCenter, "Система партнерского колл-центра")

System_Boundary(ABC_Boundary, "ABC - Банковская система") {
    Container(ABC, "ABC", "Delphi")
    ContainerDb(ABC_Db, "ABC база данных", "Oracle")
    
    Rel(ABC, ABC_Db, "Вызов процедур", "PL-SQL")
}

System_Boundary(InternetBankSystem, "Интернет-банк") {
    Container(InternetBank_Monolith, "Сервис интернет-банк", "ASP.NET MVC 4.5", "Монолит")
    ContainerDb(InternetBankDb, "База данных\n интернет-банка", "MSSQL")
    
    Container(Internet_Bank_DepositWeb, "Админ-панель депозитов", "ASP.NET Razor Pages")
    Container(InternetBank_Deposit, "Микросервис депозитов", "ASP.NET Core 8")
    Container(InternetBank_Deposit_SFTP, "SFTP сервер", "SFTP")
    ContainerDb(InternetBank_DepositDb, "База данных депозитов", "MSSQL")
    
    ContainerQueue(QueueBroker, "Брокер сообщений", "Kafka")
    
    Rel(InternetBank_Monolith, InternetBankDb, "")
    Rel(InternetBank_Deposit, InternetBank_DepositDb, "")
    
    Rel(InternetBank_Monolith, InternetBank_Deposit, "Делает запросы", "HTTP/JSON")
    Rel(Internet_Bank_DepositWeb, InternetBank_Deposit, "Делает запросы", "HTTP/JSON")
    Rel(InternetBank_Deposit, InternetBank_Deposit_SFTP, "Отправка файлов Excel")
}

System_Ext(SMS, "Телеком-оператор")

Rel(User, InternetBank_Monolith, "Использует")
Rel(EmployeeBack, ABC, "Использует")
Rel(EmployeeFront, ABC, "Использует")

Rel(ABC, SMS, "Отправка СМС")
Rel(InternetBank_Deposit, QueueBroker, "Отправка заявок на депозит")
Rel(InternetBank_Monolith, QueueBroker, "Отправка информации о платежах")
Rel(QueueBroker, ABC, "Отправка заявок")
Rel(ABC, QueueBroker, "Отправка текущей информации о ставках по депозитам")

Rel(CallCenter, Internet_Bank_DepositWeb, "Просмотр текущих ставок по депозитам")
Rel(InternetBank_Deposit_SFTP, PartnerCallCenter, "Отправка файлов Excel", "SFTP")

@enduml